@TareasApi_HostAddress = https://localhost:7023

POST {{TareasApi_HostAddress}}/tareas
Content-Type: application/json

{
  "nombre":"Tarea de prueba 2",
  "estaFinalizada": false
}
###

GET {{TareasApi_HostAddress}}/tareas

###

GET {{TareasApi_HostAddress}}/tareas/6

###

PUT {{TareasApi_HostAddress}}/tareas/6
Content-Type: application/json

{
  "nombre":"Comprar Guitarra ESP X1",
  "estaFinalizada": true
}

###

DELETE {{TareasApi_HostAddress}}/tareas/6

###

GET {{TareasApi_HostAddress}}/tareas/finalizadas

###
